
CREATE TABLE emloyees (
 emp_id SERIAL PRIMARY KEY,
 fname VARCHAR(50) NOT NULL,
 lname VARCHAR(50) NOT NULL,
 email VARCHAR(100) UNIQUE NOT NULL,
 dep VARCHAR(50) NOT NULL,
 salary NUMERIC(10, 2) CHECK s
)